version: '3.4'

networks:
  tessera-bridge:

services:
  postgres:
    container_name: tessera-postgres
    image: postgres:12.3
    restart: always
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES_DB=$PG_DATABASE
    networks:
      - tessera-bridge
